### ISSUE TITLE
Make it harder to forget to extend `LoggedRobot`

### ISSUE THREAD

**Issue by jonahsnider** [Mechanical-Advantage/AdvantageKit#31]
Forgetting to extend `LoggedRobot` in your `Robot.java` file is a very subtle mistake to make, and seems to totally break logging in a confusing way. There doesn't appear to be an obvious indicator that the issues you're having with logging are related to the `Robot` class. AdvantageKit should make it harder to do this. Adding a bit of code to enforce that `Robot` is  properly extending `LoggedRobot`.

One way you could do this is to update `Logger#start()` to accept a `LoggedRobot` as a parameter, and then instructing users to have the following in their `Robot.java` constructor:
```java
Logger.getInstance().start(this):
```

This would fail at compile-time if users were incorrectly extending from `TimedRobot` instead of `LoggedRobot`. The `start()` method doesn't actually need to do anything with the passed in robot object.

**Comment by jwbonner** [comment]
The confusion over `TimedRobot` vs `LoggedRobot` is definitely an issue. Fundamentally, inheriting from `TimedRobot` is always broken when using AdvantageKit's WPILib shims. After some discussion, we concluded that since there's no use case for `TimedRobot` or `TimesliceRobot` with AdvantageKit, it's appropriate to block inheriting from them whenever the shims are installed. 506c48e sets them as final and deprecated, triggering a compile-time error and an explanation if the user tries to use them:

<img width="815" alt="Screen Shot 2023-01-15 at 10 11 20 AM" src="https://user-images.githubusercontent.com/47046556/212549653-fd0dcd40-2cdb-4a6c-a272-42ecdad8062a.png">
