### ISSUE TITLE
Document all supported datatypes

### ISSUE THREAD

**Issue by lidor51** [Mechanical-Advantage/AdvantageKit#48]
Add to your repo a documentation page of all supported data types.

**Comment by jwbonner** [comment]
I think this is now addressed, with the new inclusion of structured data types:

https://github.com/Mechanical-Advantage/AdvantageKit/blob/main/docs/DATA-FLOW.md#simple-data-types

There's no point listing the specific struct types since that depends on WPILib support which will change over time. Plus teams can define their own types anyway.
