### ISSUE TITLE
@AutoLogOutput annotation does not work with git submodules

### ISSUE THREAD

**Issue by LuminousLlama** [Mechanical-Advantage/AdvantageKit#55]
While working on creating a git submodule to contain FRC 2930's common libraries/code moving forward, I found a situation where the `@AutoLogOutput` annotation does not work. 

I suspect the issue might be similar-ish to this one: 
https://www.chiefdelphi.com/t/advantagekit-2024-log-replay-again/442968/38

I'm not sure if the root cause of the issue is it being a git submodule or it being a grade subproject or something else entirely.

### Code explanation/What should happen
I have created 2 subsystems

one called `SubsystemGitSubmodule` lives inside the git submodule 
the other called `SubsystemBaseCode` lives in the base code 

Both contain identical code
![image](https://github.com/Mechanical-Advantage/AdvantageKit/assets/92387980/3a6c58a0-a1fe-4e34-a8af-319d24563018)

I then define both in `RobotContainer`
![image](https://github.com/Mechanical-Advantage/AdvantageKit/assets/92387980/f2037dba-5850-4287-8d96-67cb30189af4)

**EXPECTED RESULT**
When simulating robot code, we see two NT entries. `AdvantageKit/RealOutputs/SubsystemBaseCode/Test` AND `AdvantageKit/RealOutputs/SubsystemGitSubmodule/Test` 

**ACTUAL RESULT** 
Only `AdvantageKit/RealOutputs/SubsystemBaseCode/Test` is visible
![image](https://github.com/Mechanical-Advantage/AdvantageKit/assets/92387980/5df9358f-9a60-47ec-82d9-37d5babadea3)

### How to recreate 
1. clone https://github.com/LuminousLlama/AkitBugBaseCode
2. The build WILL fail. This is expected. To fix run `git submodule update --init` 
3. Run the `Java: Clean Java Language Server WorkSpace` task from the command pallet
![image](https://github.com/Mechanical-Advantage/AdvantageKit/assets/92387980/32810a24-3bd2-4076-902e-7112bd67c8c9)
4. Build should now work. Simulate the robot code and connect to advantage scope (or any NT viewer) 

Only `SubsystemBaseCode` is visible. `SubsystemGitSubmodule` Will be missing 
![image](https://github.com/Mechanical-Advantage/AdvantageKit/assets/92387980/822196d6-7f2e-4676-bde9-ce8b9fa107d0)

**Comment by jwbonner** [comment]
The issue is that the classes in the main project and submodule have different class paths. The documentation for [`@AutoLogOutput`](https://github.com/Mechanical-Advantage/AdvantageKit/blob/main/docs/RECORDING-OUTPUTS.md#autologoutput-annotation) states:

> The parent class where @AutoLogOutput is used must be instantiated within the first loop cycle, be accessible by a recursive search of the fields of Robot, and **be within the same package as Robot (or a subpackage)**. This feature is primarily intended to log outputs from subsystems and other similar classes. For classes that do not fit the criteria above, call Logger.recordOutput periodically to record outputs.

The annotations need to be identified at runtime by searching through the instantiated objects under `Robot`, and the package restriction is necessary to avoid scanning every class in WPILib, vendor libraries, etc. [Monologue](https://github.com/shueja/Monologue) solves this by requiring a `Logged` interface to be placed on every parent class, but we felt this added too much overhead when the purpose of `AutoLogOutput` is to be easier than calling `Logger.recordOutput`.

Beyond just using `Logger.recordOutput`, the easiest solution would be for us to add a method that can override the set of allowed packages for `AutoLogOutput`. It would probably look something like this in your case (this would be called in `robotInit`).

```java
AutoLogOutputManager.addPackage("org.frcteam2930.common");
```

This is a relatively simple addition, so I should be able to include it for the next release.
