### ISSUE TITLE
Serialization for WPILIB geometry classes not working in a Kotlin robot project

### ISSUE THREAD

**Issue by sswadkar** [Mechanical-Advantage/AdvantageKit#75]
AdvantageScope isn't able to read fields that are WPILIB geometry classes such as `Pose2d` and instead interprets these as just a byte array. Upon comparing the output from a Java robot project, the byte array for a given `Pose2d` object isn't fundamentally different, so I'm assuming AdvantageKit is publishing the array with type Raw instead of the corresponding WPILIB struct. Our temporary solution has been to log these classes as DoubleArray's but this doesn't work for the Swerve Visualization tab where `SwerveModuleState`s are required to be published. 

Here's our robot project and the issue is reproducable in sim (which we have running): https://github.com/team4099/Crescendo-2024

**Comment by jwbonner** [comment]
It looks like the issue is [here](https://github.com/team4099/Crescendo-2024/blob/main/src/main/kotlin/com/team4099/robot2023/util/NTSafePublisher.kt#L48) in `NTSafePublisher`. This should be `newValue.nT4Type` instead of `newValue.type.nT4Type`, consistent with the [Java version](https://github.com/Mechanical-Advantage/AdvantageKit/blob/main/junction/core/src/org/littletonrobotics/junction/networktables/NT4Publisher.java#L57). The type enum represents the type used by AdvantageKit internally, but reading the NT4 type from the value instead will allow the custom type string to override the ordinary type. These custom type strings are necessary for publishing both the struct fields themselves and the schemas used to decode them.
