### ISSUE TITLE
LogTable is not thread safe

### ISSUE THREAD

**Issue by PeterJohnson** [Mechanical-Advantage/AdvantageKit#80]
StructBuffer and ProtoBuffer are stored in a cache but there is no mutex protection around using a cached buffer, so you can end up with a data race.  This is a problem e.g. when trying to log from a separate processing thread: https://www.chiefdelphi.com/t/advantagekit-2024-log-replay-again/442968/218?u=peter_johnson

**Comment by jwbonner** [comment]
AdvantageKit's logging APIs aren't designed to be thread-safe in general, because logging values from other threads doesn't make sense with AdvantageKit's architecture. Since all values are synchronized to the loop cycle, you would end up missing values or logging values with inaccurate timestamps. Threads should log all of their values as inputs with appropriate synchronization to enable replay.

I've updated the documentation and Javadocs to warn about this issue, and suggest an alternative structure.
